### ISSUE TITLE
QuickStart Howto

### ISSUE THREAD

**Issue by whitepj** [sbcshop/Scangenie_Software#1]
Could really do with a basic tutorial to accompany this device. 
How to power (both battery, and via breakout pins). Schematic suggests 3.3v, but Li battery is nominally 3.7v.
 Is there a I2C fuel gauge?
Apologies -- these are my first steps into Aduino.
(ps. https://github.com/sbcshop/Scangenie_Software/blob/main/libraries.zip is not unzipping for me)

**Comment by sbcshop3** [comment]
You can power board with USB or connect 3.3V/5V at corresponding pins via breakout pins or connect battery. There is no I2C fuel gauge on board. And files is extracted without issue using winrar but if it is not working for you try other software.
